### ISSUE TITLE
model.ckpt file not found

### ISSUE THREAD

**Issue by DanielShemesh** [Linaqruf/kohya-trainer#13]
I am having an issue where, after training is complete, I am not finding the model.ckpt file in the expected location (/content/kohya-trainer/fine-tuned/model.ckpt). Instead, I am only finding a folder (/content/kohya-trainer/fine-tuned/last) in this location. Is there a reason why the model.ckpt file is not being generated or saved in the expected location?

**Comment by DanielShemesh** [comment]
I think I understand what happened now. The model was saved as diffusers, but I was able to successfully convert it to a .ckpt file. Is there a way to save the model originally as a .ckpt file, rather than having to convert it afterwards?

**Comment by Linaqruf** [comment]
I'm sorry for the late reply. If your pretrained model is in diffusers format, your output will be in that format as well.

If you want to save the model originally as a ckpt file without having to convert it in the next cell, you need to declare the hyperparameter `--save_model_as ckpt`. You can refer to the original code, in line 1009 of [fine_tune.py](https://github.com/Linaqruf/kohya-trainer/blob/main/diffuser_fine_tuning/fine_tune.py):

```
  parser.add_argument("--save_model_as", type=str, default=None, choices=[None, "ckpt", "safetensors", "diffusers", "diffusers_safetensors"],
                      help="format to save the model (default is same to original) / モデル保存時の形式（未指定時は元モデルと同じ）")
``` 

However, for some reason, I think you can't set `--save_model_as safetensors` in Colab because you will run out of memory anyway.

**Comment by DanielShemesh** [comment]
Would it be possible to update the Colab notebook to include an option for the user to select the desired save type for the model, using a dropdown list that includes options such as .ckpt and diffusers? This would allow users to choose the save format that works best for their needs.

**Comment by Linaqruf** [comment]
Sure, i already put`--save_model_as` hyperparameter to training cell in the latest notebook
