### ISSUE TITLE
Please help on output parameters and resuming process

### ISSUE THREAD

**Issue by ErwinTATP** [Linaqruf/kohya-trainer#29]
I would like output to be the ~150MB “additional networks” that can be mounted via extensions. However, after recent updates I can’t always get that: it’s always the ~1.5GB “full model” (I assume), only sometimes can I get the desired 150MB file. I would like to know how to get the 150MB files consistently. 

Also, if I’m understanding correctly, the previous practice of training `5_conceptA` and `10_conceptB` in each folders has been updeted into training `conceptA` 5 times, then `conceptB` 10 times from a resumed process. How can I resume that process, or is there an easier way to train both concepts in one click?

**Comment by Linaqruf** [comment]
what notebook are u using? make sure you're using [kohya-lora-finetuner](https://github.com/Linaqruf/kohya-trainer/blob/main/kohya-LoRA-finetuner.ipynb) and/or [kohya-lora-dreambooth](https://github.com/Linaqruf/kohya-trainer/blob/main/kohya-LoRA-finetuner.ipynb), then set network dim to 128 if you want your output around ~150mb

you need to put parent folder path in `train_data_directory` instead of conceptA path or conceptB path, this will help you to train both concept instead of 1 per session.

**Comment by ErwinTATP** [comment]
Yeah... just found out I had been stupid that I've used a different notebook. Closing this one...
