### ISSUE TITLE
What I'm doing wrong?

### ISSUE THREAD

**Issue by grlfo** [Linaqruf/kohya-trainer#45]
Yesterday night somehow I made it work but today I can't. The code seems to work ( except for some tensorflow errors ) but when I use the lora in SD there's no change in the image. Maybe it's because yesterday I used 51 images for the lora and today I used 105?

I upload my folder with 105 images in 512x512 to my drive, then I press all the celds till path 3. I press the cell 3.1, delete the train_data folder and put my train data folder ( previously uploaded in my drive ) in the same path, I skip 3.2, 3.3 and 4.1 cells, untick BLIP captioning and from here I press every cell till finish in 5.2. When 5.2 ends I put the .safetensors in my drive and when I try the lora in SD there's no changes in the image.

[4.2. Data Annotation](https://imgur.com/FvlRMm7)

[4.3. Create JSON file for Finetuning](https://imgur.com/fG2YNUe)

[4.4. Aspect Ratio Bucketing and Cache Latents](https://imgur.com/MuHeseX)

[5.2. Start Fine-Tuning](https://imgur.com/esvxudp)

**Comment by Linaqruf** [comment]
Hello, 

[4.2. Data Annotation](https://imgur.com/FvlRMm7)

You're good. There's a bug where TensorFlow couldn't find the TensorRT libinver folder in colab, but it won't affect the training.

[4.3. Create JSON file for Finetuning](https://imgur.com/fG2YNUe)

This is normal, mainly because it couldn't find any captions or meta_cap.json to store in meta_clean.json, but the tags were stored properly. You can always check the meta_clean.json to see if your captions/tags are stored in the JSON file.

[4.4. Aspect Ratio Bucketing and Cache Latents](https://imgur.com/MuHeseX)

This is also normal, but I suggest not cropping your dataset to 512x512 again if you're using the Kohya script, as it will be trained at a non-square resolution.

[5.2. Start Fine-Tuning](https://imgur.com/esvxudp)
This is also normal, all important hyperparameters are used properly and your model has finished training.

All I can think of:

- Your LoRA model is probably underfitted because you only trained it for 10 epochs. You may need more epochs.
- I wouldn't recommend using the built-in LoRA feature in the web UI, as I haven't used it. You'll need to install the extensions. You can also check if your model was trained properly by reading the metadata inside the extension.
- If you're already using the extension, it's probably because you forgot to set enable LoRA, which I also often forget to check.
- Adjust your LoRA weight to see the differences.

You can check my latest LoRA trained from yesterday update. 
![image](https://user-images.githubusercontent.com/50163983/215995302-46e2f865-5ca6-43a5-8682-f6d073933969.png)

**Comment by grlfo** [comment]
> This is also normal, but I suggest not cropping your dataset to 512x512 again if you're using the Kohya script, as it will be trained at a non-square resolution.

I resize the img to 512 because I thought it was obligatory for training, can I train the lora with the original size ? (3393x4200)

> Your LoRA model is probably underfitted because you only trained it for 10 epochs. You may need more epochs.

I thought 10 was a lot, how many epoch do you recommend?

> I wouldn't recommend using the built-in LoRA feature in the web UI, as I haven't used it. You'll need to install the extensions. You can also check if your model was trained properly by reading the metadata inside the extension.

I'm running "kohya-LoRA-finetuner.ipynb" and SD both in colab and using the "sd-webui-additional-networks", what extension are you referring to?

> If you're already using the extension, it's probably because you forgot to set enable LoRA, which I also often forget to check.
Adjust your LoRA weight to see the differences.

I always doblecheck these, I tried others lora and they work perfectly fine and the lora I did made no change in the image, also tried changing the weight to the max and is the same.

I thought that the problem maybe was the quantity of img (105) or skipping a necessary cell (3.2, 3.3, 4.1) but from what you tell me, must be the epoch.

Thanks for replying me and sorry for bothering you Linaqruf, I'm new in all of this of colab, github and SD, also english it's not my native language so it's a bit tough.

**Comment by Linaqruf** [comment]
I'm sorry, too focus updating my notebook

>I resize the img to 512 because I thought it was obligatory for training, can I train the lora with the original size ? (3393x4200)

Yeah, you can train with the original aspect ratio, not the image size, so you dont need to resize it to square resolution anymore.

>AI thought 10 was a lot, how many epoch do you recommend?

Actually I want to change the max_train_count identifier from `num_epochs` to `max_train_steps` it can be speficic to use than num_epochs.

I think 20 epochs 10 repeats are good enough

>I'm running "kohya-LoRA-finetuner.ipynb" and SD both in colab and using the "sd-webui-additional-networks", what extension are you referring to?

Yeah, that `sd-webui-additional-networks` 

```LoRA weight: 1, model: yoshi(060743c5)
Error running process: /content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 386, in process
    script.process(p, *script_args)
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 177, in process
    network, info = lora_compvis.create_network_and_apply_compvis(du_state_dict, weight, text_encoder, unet)
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 73, in create_network_and_apply_compvis
    network_dim = min([s for s in size if s > 1])
ValueError: min() arg is an empty sequence
```
You should update your extensions, there are 2-3 thread with the same issue and they can load the model after updating the extensions. If you still facing this issue, i recommend to open issue ticket here : https://github.com/kohya-ss/sd-webui-additional-networks

**Comment by grlfo** [comment]
> You should update your extensions, there are 2-3 thread with the same issue and they can load the model after updating the extensions. If you still facing this issue, i recommend to open issue ticket here : https://github.com/kohya-ss/sd-webui-additional-networks

Thanks you @Linaqruf now it works perfectly

**Comment by grlfo** [comment]
> You should update your extensions, there are 2-3 thread with the same issue and they can load the model after updating the extensions. If you still facing this issue, i recommend to open issue ticket here : https://github.com/kohya-ss/sd-webui-additional-networks

Thanks you @Linaqruf now it works perfectly

**Comment by Linaqruf** [comment]
No problem, I'm sorry for the late answer!
