### ISSUE TITLE
Kohya colab not working properly?

### ISSUE THREAD

**Issue by Atoli** [Linaqruf/kohya-trainer#53]
I frequently use the Kohya colab trainer, last time i used it was probably a few days ago, jan 28th, with great results.

I used it today but it does not work anymore, i set all the parameters and datasets like i always do, it does the "training" but the resulting .safetensor does absolutely nothing when tested, the generation using the prompts it was trained on look nothing like the training data.

These are my settings, am i doing something wrong?:

![1](https://user-images.githubusercontent.com/43733214/216709779-65028e44-bb52-44e3-80db-dd950f440d51.png)

Tried multiple times with a different amount of epochs ranging from 6 to 20, changing the dataset txt files to be more precise, changing the regularization steps, among other number of things, but no improvement. The resulting safetensor does nothing.

As a reference, last time i tried it and worked the project name was not a dragalia lost LoRA (don't remember what was the last project name when it worked fine, i think it was "hito-komoru"?), that's the only new thing i noticed when i tried to train a dataset today.

**Comment by Linaqruf** [comment]
Hello, 
What colab notebook did you use before? we have 4 colab notebook now to be precise
| Notebook Name | Description | Link |
| --- | --- | --- |
| [Kohya LoRA Dreambooth](https://github.com/Linaqruf/kohya-trainer/blob/main/kohya-LoRA-dreambooth.ipynb) | LoRA Training (Dreambooth method) | [![](https://img.shields.io/static/v1?message=Open%20in%20Colab&logo=googlecolab&labelColor=5c5c5c&color=0f80c1&label=%20&style=for-the-badge)](https://colab.research.google.com/github/Linaqruf/kohya-trainer/blob/main/kohya-LoRA-dreambooth.ipynb) |
| [Kohya LoRA Fine-Tuning](https://github.com/Linaqruf/kohya-trainer/blob/main/kohya-LoRA-finetuner.ipynb) | LoRA Training (Fine-tune method) | [![](https://img.shields.io/static/v1?message=Open%20in%20Colab&logo=googlecolab&labelColor=5c5c5c&color=0f80c1&label=%20&style=for-the-badge)](https://colab.research.google.com/github/Linaqruf/kohya-trainer/blob/main/kohya-LoRA-finetuner.ipynb) |
| [Kohya Trainer](https://github.com/Linaqruf/kohya-trainer/blob/main/kohya-trainer.ipynb) | Native Training | [![](https://img.shields.io/static/v1?message=Open%20in%20Colab&logo=googlecolab&labelColor=5c5c5c&color=0f80c1&label=%20&style=for-the-badge)](https://colab.research.google.com/github/Linaqruf/kohya-trainer/blob/main/kohya-trainer.ipynb) |
| [Kohya Dreambooth](https://github.com/Linaqruf/kohya-trainer/blob/main/kohya-dreambooth.ipynb) | Dreambooth Training | [![](https://img.shields.io/static/v1?message=Open%20in%20Colab&logo=googlecolab&labelColor=5c5c5c&color=0f80c1&label=%20&style=for-the-badge)](https://colab.research.google.com/github/Linaqruf/kohya-trainer/blob/main/kohya-dreambooth.ipynb) |

And based on the parameter table you shared, you're not using our main notebook  [Kohya Trainer](https://github.com/Linaqruf/kohya-trainer/blob/main/kohya-trainer.ipynb) to train normal Stable Diffusion model, but [Kohya LoRA Dreambooth](https://github.com/Linaqruf/kohya-trainer/blob/main/kohya-LoRA-dreambooth.ipynb) | LoRA Training (Dreambooth method) to train LoRA model with dreambooth method.

I'm sorry if It's confusing, especially I put the main notebook below LoRA notebook. Because LoRA seems to be a trend and people often training using wrong notebook.

**Comment by Atoli** [comment]
Greetings.

I have been using this one:  https://colab.research.google.com/github/Linaqruf/kohya-trainer/blob/main/kohya-LoRA-dreambooth.ipynb#scrollTo=WNn0g1pnHfk5

I tried Both LoRA fine tuning and trainer but both gave me errors involving a .yaml file for the former and a meta.json for the latter so i gave up on them.

**Comment by Linaqruf** [comment]
Can you explain what error?

**Comment by Atoli** [comment]
Greetings.

I will use both right now to show you the problems/issues i run into. I believe the errors happen because of my lack of understanding rather than an error in the notebook.

Kohya's fine tuning:

![finetuner](https://user-images.githubusercontent.com/43733214/216775862-754ab620-9936-44d0-bc50-3c3ee0dd1e86.PNG)

Kohya's trainer:

![kohya trainer](https://user-images.githubusercontent.com/43733214/216775869-1d82edb7-0ec7-40d7-ae0c-b5042f31c221.PNG)

While they not working is annoying, it ultimately does not matter, as LoRA dreambooth (https://colab.research.google.com/github/Linaqruf/kohya-trainer/blob/main/kohya-LoRA-dreambooth.ipynb#scrollTo=WNn0g1pnHfk5) is the one i use to train .safetensor files. The problem is that THAT one now is not working properly.

The resulting safetensors before were AMAZING until a few days ago, now the resulting safetensor does nothing. I just tested again today (Feb 4th) but nothing, the result safetensor does not affect the image generation at all. 
Check the opening post for the image of the settings i used that gave me a faulty result.

Extra information: 

All trained safetensors i trained with LoRA dreamboth that work have the same size regardless size of dataset: 147.534kb
The newer ones that do not work all have a different size: 147.570kb

Might not be much, but it's an interesting change i noticed.

**Comment by Fannovel16** [comment]
Try removing --shuffle_caption

**Comment by Atoli** [comment]
Greetings.

Tried removing --shuffle_caption but nothing, the trained safetensor is just a useless file that does nothing to the generation of art.

To discard the problem being related to my dataset, i re-trained another LoRA i had trained before with excellent results a week ago...the result was a safetensor that does nothing.

So, i believe the problem seem to be related to the notebook.

**Comment by Linaqruf** [comment]
Hello, sorry for the late reply

>Kohya's fine tuning:

i guess you're using %cd /content/drive/ instead of /content/
you can't set `/content/drive/` as active directory to process, create, or editing, but instead use `/content/drive/MyDrive/<file-or-folder-here`, it's not my notebook mistake but colab rules.

>Kohya Trainer
I'm guessing you're forgot to create `meta_lat.json` from bucketing cell or even `meta_clean.json` to save all tags and caption

Can you explain how it's not working? Like:
- Posting x/y plot to compare images when using LoRA and not
- Posting Console message history where the error explained, maybe u need to update extension or something
- Share the metadata, my notebook provide a cell to read metadata from `.safetensors` LoRA

You can try to run your LoRA from my inference cell before deploying to webui.

**Comment by Atoli** [comment]
Greetings.

I have absolutely NO IDEA what happened, but today (February 9th), dreambooth LoRA training (this link: https://colab.research.google.com/github/Linaqruf/kohya-trainer/blob/main/kohya-LoRA-dreambooth.ipynb#scrollTo=reMcN0bM_o53) is now working fine.

I am doing eveything i always did and now the result are actually working LoRA safetensor files.

I hope it does not break again.

I do not know what was the problem (i trained like 5+ LoRA files when it was broken and all were bad) but it seems it's not an issue anymore.,,so...i cannot provide information about what's bugged because it's not bugged anymore.

I thought in using the "Validating LoRA weights" (i think that's the metadata you speak of?) with one of the buggy files i have, but i got the following error:

`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-28-0c4373a5ce1d>](https://localhost:8080/#) in <module>
     46 
     47 if __name__ == '__main__':
---> 48   main(network_weights, no_verbose)

[<ipython-input-28-0c4373a5ce1d>](https://localhost:8080/#) in main(file, verbose)
     36       if metadata is not None:
     37         if not verbose:
---> 38           metadata["ss_bucket_info"] = json.loads(metadata["ss_bucket_info"].replace("\\", ""))
     39           metadata["ss_tag_frequency"] = json.loads(metadata["ss_tag_frequency"].replace("\\", ""))
     40         metadata["ss_dataset_dirs"] = json.loads(metadata["ss_dataset_dirs"].replace("\\", ""))

KeyError: 'ss_bucket_info'`
