### ISSUE TITLE
Suddenly it broke.

### ISSUE THREAD

**Issue by GeneralAwareness** [Linaqruf/kohya-trainer#60]
I am unsure what has happened but Colab will not work.  I grabbed the new notebook to find the same error.

/content/kohya-trainer
2023-02-06 07:07:39.308404: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-06 07:07:40.336883: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-02-06 07:07:40.337039: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-02-06 07:07:40.337067: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-02-06 07:07:43.945811: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-06 07:07:44.654456: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-02-06 07:07:44.654608: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-02-06 07:07:44.654629: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
prepare tokenizer
update token length: 225
Use DreamBooth method.
prepare train images.
found directory 20_usu frog contains 15 image files
300 train images with repeating.
prepare reg images.
found directory 1_frog contains 50 image files
50 reg images.
loading image sizes.
100% 65/65 [00:00<00:00, 725.58it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (320, 1280), count: 0
bucket 1: resolution (384, 1280), count: 0
bucket 2: resolution (448, 1216), count: 0
bucket 3: resolution (448, 1280), count: 0
bucket 4: resolution (512, 1088), count: 0
bucket 5: resolution (512, 1152), count: 0
bucket 6: resolution (576, 960), count: 0
bucket 7: resolution (576, 1024), count: 0
bucket 8: resolution (640, 896), count: 0
bucket 9: resolution (704, 832), count: 0
bucket 10: resolution (768, 768), count: 600
bucket 11: resolution (832, 704), count: 0
bucket 12: resolution (896, 640), count: 0
bucket 13: resolution (960, 576), count: 0
bucket 14: resolution (1024, 576), count: 0
bucket 15: resolution (1088, 512), count: 0
bucket 16: resolution (1152, 512), count: 0
bucket 17: resolution (1216, 448), count: 0
bucket 18: resolution (1280, 320), count: 0
bucket 19: resolution (1280, 384), count: 0
bucket 20: resolution (1280, 448), count: 0
mean ar error (without repeats): 0.0
prepare accelerator
Using accelerator 0.15.0 or above.
load StableDiffusion checkpoint
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
Replace CrossAttention.forward to use xformers
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_network.py', '--v2', '--v_parameterization', '--network_dim=8', '--network_alpha=8', '--network_module=networks.lora', '--learning_rate=0.0001', '--text_encoder_lr=5e-05', '--no_metadata', '--lr_scheduler=constant', '--pretrained_model_name_or_path=/content/drive/MyDrive/pre_trained_model/stable-diffusion-2-1-768v.ckpt', '--caption_extension=.txt', '--train_data_dir=/content/drive/MyDrive/SAMPLE_IMAGES/Frog_Lora/train', '--reg_data_dir=/content/drive/MyDrive/SAMPLE_IMAGES/Frog_Lora/reg', '--output_dir=/content/drive/MyDrive/SAMPLE_IMAGES/Frog_Lora/model', '--prior_loss_weight=1.0', '--output_name=Frog', '--mixed_precision=fp16', '--save_precision=fp16', '--save_n_epoch_ratio=2', '--save_model_as=safetensors', '--resolution=768', '--enable_bucket', '--min_bucket_reso=320', '--max_bucket_reso=1280', '--cache_latents', '--train_batch_size=1', '--max_token_length=225', '--use_8bit_adam', '--max_train_epochs=1', '--gradient_checkpointing', '--gradient_accumulation_steps=1', '--logging_dir=/content/dreambooth/logs', '--log_prefix=Frog', '--shuffle_caption', '--xformers']' died with <Signals.SIGKILL: 9>.

Do you see anything?

**Comment by Linaqruf** [comment]
Are you running on colab pro gpu? probably that because wrong xformers installed, my notebook only support T4 xformers for now, cuz I can't test on different xformers when i'm still using colab free.

You can install another xformers by compile it yourself or using pre-compiled wheels shared by github user like :

- https://github.com/camenduru/stable-diffusion-webui-colab/releases, and
- https://github.com/TheLastBen/fast-stable-diffusion/tree/main/precompiled

If you're using colab free then probably it's a Colab bug after the Ubuntu update two weeks ago. There's an unusual high RAM usage issue when loading an SD model. I temporarily fixed it in the [Kohya LoRA Fine-Tuning](https://github.com/Linaqruf/kohya-trainer/blob/main/kohya-LoRA-finetuner.ipynb) and [Kohya Trainer](https://github.com/Linaqruf/kohya-trainer/blob/main/kohya-trainer.ipynb) notebooks by loading the model on the GPU instead of the CPU. However, for some reason, it didn't work with[Kohya LoRA Dreambooth](https://github.com/Linaqruf/kohya-trainer/blob/main/kohya-LoRA-dreambooth.ipynb) and [Kohya Dreambooth](https://github.com/Linaqruf/kohya-trainer/blob/main/kohya-dreambooth.ipynb). This caused the DreamBooth data loader to fail to load image latents.

For now, I suggest to :
- Use another pretrained model
- Use diffusers version of the model, put `user-id/model-id` to `pretrained_model_path` field (e.g. `stabilityai/stable-diffusion-2-1`) and it will downloading the model using huggingface hub when the training started
- Use (half) FP16 version of the model

**Comment by GeneralAwareness** [comment]
Yes, I can't run anything LoRA related as of midnight my time.  Just poof.  I had disconnects, and all kinds of weird things so now I can't run any of these.  Colab free is what I use.

**Comment by Linaqruf** [comment]
i mean, instead of this
![image](https://user-images.githubusercontent.com/50163983/216946790-2df65adb-3530-447f-8309-99c3f19f8f8f.png)

register the pretrained model like this
![image](https://user-images.githubusercontent.com/50163983/216946615-073b5c9d-342f-4f0d-8e2a-e988c0b5121a.png)

it will download folder inside this repo, instead of using ckpt format to train, https://huggingface.co/stabilityai/stable-diffusion-2-1/tree/main
![image](https://user-images.githubusercontent.com/50163983/216947044-0415fef0-562d-4003-a90c-28853260f92a.png)

**Comment by GeneralAwareness** [comment]
Ahhh, great.  I wonder if this is a bug or a passive way to stop training?  They did this for deepfakes in 2018 then came out and outright banned people who were training when caught (they easily caught them back then).

**Comment by GeneralAwareness** [comment]
> > I had disconnects, and all kinds of weird things so now I can't run any of these
> 
> Oh this? GPU and compute units in colab free is not completely free. There is a limit, like max 12h/day, It can decreased till 6h-2h if you're using too much resource, for example training AI Model. If you got limit you should wait till next day for reset.
> 
> I suggest to set your `output_dir` to your google drive or run `upload to huggingface` if you leave the training for sleep.

No, I don't mean GPU I mean TCPIP disconnects, and all other kinds of weird things.

**Comment by Linaqruf** [comment]
oh thats weird, never had that issue,
is your datasets sensitive?

**Comment by GeneralAwareness** [comment]
Luckily, they aren't.  It was strange because at precisely midnight my time, and for about 10 mins, all of it hit where ever since I can't train.

**Comment by GeneralAwareness** [comment]
![image](https://user-images.githubusercontent.com/124339252/216950999-370d1934-f146-47a1-9d05-792534c2539e.png)
![image](https://user-images.githubusercontent.com/124339252/216951320-3264087a-4132-4615-82ff-6fcc435e7fa9.png)
Tells me I am downloading safetensors scrolling into oblivion over and over. 50+ times.

![image](https://user-images.githubusercontent.com/124339252/216951740-57cf95a3-a454-408f-8661-b8dae434d648.png)

It worked though.

**Comment by GeneralAwareness** [comment]
Isn't there some way I can save that on my google drive so it doesn't have to download it each time?

**Comment by GeneralAwareness** [comment]
Oh, I got her example to compile in 2.1 768 using diffusers that ckpt refused.  Seems this was a blessing in disguise if I could just get that over to my gdrive to use.  Was VERY fast training too (1.53s/it vs 13.xx).

![image](https://user-images.githubusercontent.com/124339252/216957798-a36e3f68-9357-4200-9951-ad9facfb0eb4.png)

**Comment by GeneralAwareness** [comment]
You know I downloaded then uploaded the diffusers and Kohya refused to work with it as it said it was a directory.  WHY?
